
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taletime.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

lorem: |
  Lorem ipsum dolor amet listicle subway tile drinking vinegar retro crucifix vice distillery cray pickled paleo next level offal hexagon man braid. Freegan small batch leggings single-origin coffee tumblr tote bag lo-fi adaptogen letterpress. Iceland semiotics flexitarian, single-origin coffee man bun seitan salvia selvage asymmetrical pug wayfarers microdosing wolf farm-to-table photo booth. Vexillologist cred la croix raw denim snackwave meditation church-key coloring book whatever intelligentsia blog activated charcoal bicycle rights typewriter.

  Pork belly locavore mustache, lo-fi leggings deep v raw denim. YOLO food truck fam, hell of shabby chic cornhole neutra master cleanse woke single-origin coffee photo booth live-edge. Blog meggings keffiyeh thundercats artisan deep v pour-over cray migas. Succulents raclette lo-fi gastropub la croix. Wolf mlkshk offal, la croix lumbersexual adaptogen fam flexitarian normcore. Narwhal selvage vexillologist, viral distillery live-edge actually man bun gentrify enamel pin freegan kickstarter poutine pitchfork. Meh schlitz aesthetic hella trust fund.

  Polaroid kinfolk beard, kale chips ugh lyft gluten-free live-edge PBR&B unicorn. Iceland venmo marfa swag echo park craft beer. Raw denim celiac unicorn try-hard, hot chicken kinfolk humblebrag farm-to-table offal wayfarers live-edge. Shaman master cleanse bicycle rights, 8-bit banh mi distillery kickstarter skateboard blue bottle woke edison bulb vaporware keytar normcore hoodie. Raclette marfa iPhone unicorn photo booth tote bag. Neutra VHS chillwave truffaut, sartorial pok pok hot chicken kogi street art iceland.

contributing: |
  Since this is an open source project, everyone can help making TaleTime better. You will find the complete source code on <a href="https://github.com/TaleTime/TaleTime">GitHub</a>, where you can also get some more information on how to contribute.

  When implementing a new feature or fixing a bug, please make sure that your code follows the same style as the existing codebase and try writing your code as understandable as possible. You should also test your changes and only commit them if they don't break anything. Your comments should be in English.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
